server:
  #   SSL证书
  ssl:
    key-store: classpath:anchwngb.cn.pfx
    key-store-password: v5my46148ph3t
    key-store-type: PKCS12

spring:
  data:
    # redis配置
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: 'eBI6YnFIEQ5'
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/super_bot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: super_bot
    password: 'hthWC78MHFZ7KACK'

chat-bridge:
  # 敏感数据加密密钥（128bit，使用Base64编码）
  business-key: 1tDZ7omDsiHpVtqGp7Aoiw==


